const restaurants = [
  {
    image: "Eigth",
    name: "Punjabi Rasoi",
    rating: "4.9",
    food_type: "Thai",
    price_for_food: 852,
    location: "Scheme 54",
    distance: "8.5",
    offers: 25,
    alcohol: true,
    restaurant_open_time: 17,
    restaurant_close_time: 5,
  },
  {
    image: "nine",
    name: "Curry Leaf",
    rating: "4.4",
    food_type: "Korean",
    price_for_food: 923,
    location: "Treasure Island Mall",
    distance: "10.8",
    offers: 36,
    alcohol: true,
    restaurant_open_time: 17,
    restaurant_close_time: 5,
  },
  {
    image: "First",
    name: "Masala Magic",
    rating: "2.7",
    food_type: "South Indian",
    price_for_food: 1112,
    location: "Vijay Nagar",
    distance: "7.7",
    offers: 49,
    alcohol: false,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "fourth",
    name: "Thali Tales",
    rating: "1.5",
    food_type: "French",
    price_for_food: 1354,
    location: "MG Road",
    distance: "6.8",
    offers: 44,
    alcohol: false,
    restaurant_open_time: 23,
    restaurant_close_time: 11,
  },
  {
    image: "fifth",
    name: "Kebab Kingdom",
    rating: "2.4",
    food_type: "French",
    price_for_food: 1389,
    location: "Geeta Bhawan",
    distance: "5.3",
    offers: 17,
    alcohol: false,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "tenth",
    name: "Paneer Palace",
    rating: "1.0",
    food_type: "Korean",
    price_for_food: 130,
    location: "New Palasia",
    distance: "6.6",
    offers: 8,
    alcohol: false,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "nine",
    name: "Royal Darbar",
    rating: "4.7",
    food_type: "Thai",
    price_for_food: 2328,
    location: "Treasure Island Mall",
    distance: "2.2",
    offers: 35,
    alcohol: true,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "Eigth",
    name: "Curry Leaf",
    rating: "4.9",
    food_type: "North Indian",
    price_for_food: 131,
    location: "South Tukoganj",
    distance: "6.5",
    offers: 16,
    alcohol: false,
    restaurant_open_time: 23,
    restaurant_close_time: 11,
  },
  {
    image: "nine",
    name: "Namaste Bistro",
    rating: "3.2",
    food_type: "Mediterranean",
    price_for_food: 637,
    location: "Geeta Bhawan",
    distance: "4.8",
    offers: 50,
    alcohol: true,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "sixth",
    name: "Biryani House",
    rating: "2.0",
    food_type: "Lebanese",
    price_for_food: 1357,
    location: "Treasure Island Mall",
    distance: "8.9",
    offers: 41,
    alcohol: false,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "tenth",
    name: "Chutney & Co.",
    rating: "4.9",
    food_type: "South Indian",
    price_for_food: 1484,
    location: "New Palasia",
    distance: "8.2",
    offers: 9,
    alcohol: true,
    restaurant_open_time: 19,
    restaurant_close_time: 7,
  },
  {
    image: "fifth",
    name: "Thali Tales",
    rating: "3.2",
    food_type: "Vietnamese",
    price_for_food: 710,
    location: "Bhawarkua",
    distance: "4.6",
    offers: 53,
    alcohol: false,
    restaurant_open_time: 16,
    restaurant_close_time: 4,
  },
  {
    image: "fifth",
    name: "Chai & Chapati",
    rating: "1.2",
    food_type: "Indian",
    price_for_food: 2215,
    location: "Vijay Nagar",
    distance: "1.0",
    offers: 41,
    alcohol: false,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "Eigth",
    name: "Himalayan Hut",
    rating: "2.0",
    food_type: "Turkish",
    price_for_food: 165,
    location: "Bhawarkua",
    distance: "10.0",
    offers: 36,
    alcohol: false,
    restaurant_open_time: 7,
    restaurant_close_time: 19,
  },
  {
    image: "fifth",
    name: "Golden Temple Kitchen",
    rating: "2.8",
    food_type: "Middle Eastern",
    price_for_food: 1782,
    location: "New Palasia",
    distance: "10.6",
    offers: 53,
    alcohol: false,
    restaurant_open_time: 8,
    restaurant_close_time: 20,
  },
  {
    image: "nine",
    name: "Paneer Palace",
    rating: "2.1",
    food_type: "South Indian",
    price_for_food: 1291,
    location: "Treasure Island Mall",
    distance: "2.6",
    offers: 8,
    alcohol: false,
    restaurant_open_time: 19,
    restaurant_close_time: 7,
  },
  {
    image: "fifth",
    name: "Masala Magic",
    rating: "1.9",
    food_type: "Fusion",
    price_for_food: 2186,
    location: "Bhawarkua",
    distance: "5.3",
    offers: 22,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "second",
    name: "Curry Leaf",
    rating: "2.4",
    food_type: "Vietnamese",
    price_for_food: 333,
    location: "Geeta Bhawan",
    distance: "2.4",
    offers: 7,
    alcohol: false,
    restaurant_open_time: 11,
    restaurant_close_time: 23,
  },
  {
    image: "second",
    name: "Himalayan Hut",
    rating: "3.9",
    food_type: "Thai",
    price_for_food: 830,
    location: "Scheme 54",
    distance: "1.3",
    offers: 6,
    alcohol: true,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "First",
    name: "Mango Masala",
    rating: "1.3",
    food_type: "American",
    price_for_food: 2429,
    location: "Rau",
    distance: "7.1",
    offers: 31,
    alcohol: true,
    restaurant_open_time: 24,
    restaurant_close_time: 12,
  },
  {
    image: "fourth",
    name: "Tandoori Nights",
    rating: "1.5",
    food_type: "Thai",
    price_for_food: 2295,
    location: "Geeta Bhawan",
    distance: "9.6",
    offers: 42,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "third",
    name: "Saffron Soul",
    rating: "3.2",
    food_type: "Italian",
    price_for_food: 195,
    location: "Scheme 54",
    distance: "8.6",
    offers: 38,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "fourth",
    name: "Kebab Kingdom",
    rating: "1.7",
    food_type: "Indian",
    price_for_food: 487,
    location: "Vijay Nagar",
    distance: "5.1",
    offers: 47,
    alcohol: false,
    restaurant_open_time: 10,
    restaurant_close_time: 22,
  },
  {
    image: "third",
    name: "Street Spice",
    rating: "2.9",
    food_type: "South Indian",
    price_for_food: 178,
    location: "Vijay Nagar",
    distance: "7.5",
    offers: 14,
    alcohol: false,
    restaurant_open_time: 7,
    restaurant_close_time: 19,
  },
  {
    image: "third",
    name: "Thali Tales",
    rating: "4.8",
    food_type: "Indian",
    price_for_food: 1075,
    location: "Vijay Nagar",
    distance: "1.7",
    offers: 48,
    alcohol: false,
    restaurant_open_time: 14,
    restaurant_close_time: 2,
  },
  {
    image: "fourth",
    name: "Mango Masala",
    rating: "1.1",
    food_type: "North Indian",
    price_for_food: 2197,
    location: "Vijay Nagar",
    distance: "5.1",
    offers: 15,
    alcohol: false,
    restaurant_open_time: 16,
    restaurant_close_time: 4,
  },
  {
    image: "First",
    name: "Thali Tales",
    rating: "4.1",
    food_type: "Korean",
    price_for_food: 1523,
    location: "Sapna Sangeeta",
    distance: "7.8",
    offers: 13,
    alcohol: false,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "tenth",
    name: "Dosa Delight",
    rating: "4.5",
    food_type: "South Indian",
    price_for_food: 1868,
    location: "Vijay Nagar",
    distance: "8.4",
    offers: 52,
    alcohol: true,
    restaurant_open_time: 11,
    restaurant_close_time: 23,
  },
  {
    image: "seventh",
    name: "Masala Magic",
    rating: "1.9",
    food_type: "Spanish",
    price_for_food: 1354,
    location: "New Palasia",
    distance: "4.7",
    offers: 47,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "third",
    name: "Kebab Kingdom",
    rating: "3.7",
    food_type: "North Indian",
    price_for_food: 1494,
    location: "Scheme 54",
    distance: "5.9",
    offers: 49,
    alcohol: true,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "second",
    name: "Chutney & Co.",
    rating: "4.4",
    food_type: "Vietnamese",
    price_for_food: 699,
    location: "Geeta Bhawan",
    distance: "6.8",
    offers: 11,
    alcohol: false,
    restaurant_open_time: 17,
    restaurant_close_time: 5,
  },
  {
    image: "fifth",
    name: "Chutney & Co.",
    rating: "3.1",
    food_type: "Lebanese",
    price_for_food: 1486,
    location: "Geeta Bhawan",
    distance: "5.3",
    offers: 40,
    alcohol: false,
    restaurant_open_time: 17,
    restaurant_close_time: 5,
  },
  {
    image: "second",
    name: "Chutney & Co.",
    rating: "2.0",
    food_type: "Continental",
    price_for_food: 228,
    location: "Rau",
    distance: "10.5",
    offers: 7,
    alcohol: false,
    restaurant_open_time: 19,
    restaurant_close_time: 7,
  },
  {
    image: "fourth",
    name: "Chai & Chapati",
    rating: "1.8",
    food_type: "Chinese",
    price_for_food: 1868,
    location: "Bhawarkua",
    distance: "5.8",
    offers: 31,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "fifth",
    name: "Golden Temple Kitchen",
    rating: "4.8",
    food_type: "Middle Eastern",
    price_for_food: 1357,
    location: "New Palasia",
    distance: "10.8",
    offers: 8,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "third",
    name: "Himalayan Hut",
    rating: "3.6",
    food_type: "Indian",
    price_for_food: 2270,
    location: "Sapna Sangeeta",
    distance: "5.7",
    offers: 37,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "seventh",
    name: "Dosa Delight",
    rating: "1.1",
    food_type: "Thai",
    price_for_food: 309,
    location: "Sapna Sangeeta",
    distance: "10.5",
    offers: 14,
    alcohol: false,
    restaurant_open_time: 19,
    restaurant_close_time: 7,
  },
  {
    image: "sixth",
    name: "Biryani House",
    rating: "4.4",
    food_type: "Middle Eastern",
    price_for_food: 259,
    location: "Geeta Bhawan",
    distance: "5.8",
    offers: 12,
    alcohol: false,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "tenth",
    name: "Mango Masala",
    rating: "1.7",
    food_type: "Spanish",
    price_for_food: 2306,
    location: "Treasure Island Mall",
    distance: "9.2",
    offers: 44,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "First",
    name: "Dosa Delight",
    rating: "3.6",
    food_type: "American",
    price_for_food: 204,
    location: "Treasure Island Mall",
    distance: "2.8",
    offers: 49,
    alcohol: false,
    restaurant_open_time: 11,
    restaurant_close_time: 23,
  },
  {
    image: "fifth",
    name: "Dosa Delight",
    rating: "3.8",
    food_type: "Japanese",
    price_for_food: 571,
    location: "South Tukoganj",
    distance: "1.3",
    offers: 27,
    alcohol: true,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "sixth",
    name: "Masala Magic",
    rating: "4.7",
    food_type: "Chinese",
    price_for_food: 1806,
    location: "New Palasia",
    distance: "9.6",
    offers: 49,
    alcohol: true,
    restaurant_open_time: 9,
    restaurant_close_time: 21,
  },
  {
    image: "third",
    name: "Golden Temple Kitchen",
    rating: "1.8",
    food_type: "Indian",
    price_for_food: 326,
    location: "Bhawarkua",
    distance: "3.0",
    offers: 47,
    alcohol: false,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "Eigth",
    name: "Street Spice",
    rating: "3.6",
    food_type: "Chinese",
    price_for_food: 254,
    location: "Rau",
    distance: "7.9",
    offers: 41,
    alcohol: false,
    restaurant_open_time: 7,
    restaurant_close_time: 19,
  },
  {
    image: "sixth",
    name: "Himalayan Hut",
    rating: "4.8",
    food_type: "South Indian",
    price_for_food: 1133,
    location: "Rau",
    distance: "10.4",
    offers: 9,
    alcohol: false,
    restaurant_open_time: 23,
    restaurant_close_time: 11,
  },
  {
    image: "tenth",
    name: "Biryani House",
    rating: "1.3",
    food_type: "Indian",
    price_for_food: 1056,
    location: "Scheme 54",
    distance: "1.4",
    offers: 26,
    alcohol: false,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "tenth",
    name: "Thali Tales",
    rating: "1.3",
    food_type: "French",
    price_for_food: 575,
    location: "Treasure Island Mall",
    distance: "10.4",
    offers: 25,
    alcohol: false,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "nine",
    name: "Himalayan Hut",
    rating: "1.3",
    food_type: "French",
    price_for_food: 400,
    location: "MG Road",
    distance: "5.9",
    offers: 27,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "nine",
    name: "Punjabi Rasoi",
    rating: "3.1",
    food_type: "North Indian",
    price_for_food: 299,
    location: "Sapna Sangeeta",
    distance: "4.2",
    offers: 32,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "third",
    name: "Punjabi Rasoi",
    rating: "1.5",
    food_type: "American",
    price_for_food: 1955,
    location: "New Palasia",
    distance: "6.5",
    offers: 50,
    alcohol: false,
    restaurant_open_time: 24,
    restaurant_close_time: 12,
  },
  {
    image: "First",
    name: "Punjabi Rasoi",
    rating: "2.1",
    food_type: "Italian",
    price_for_food: 204,
    location: "South Tukoganj",
    distance: "3.0",
    offers: 48,
    alcohol: false,
    restaurant_open_time: 8,
    restaurant_close_time: 20,
  },
  {
    image: "Eigth",
    name: "Curry Leaf",
    rating: "4.7",
    food_type: "Japanese",
    price_for_food: 1965,
    location: "Treasure Island Mall",
    distance: "5.5",
    offers: 23,
    alcohol: false,
    restaurant_open_time: 11,
    restaurant_close_time: 23,
  },
  {
    image: "Eigth",
    name: "Dosa Delight",
    rating: "3.7",
    food_type: "Greek",
    price_for_food: 732,
    location: "Geeta Bhawan",
    distance: "5.6",
    offers: 39,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "fifth",
    name: "Spice Junction",
    rating: "1.8",
    food_type: "Mexican",
    price_for_food: 1085,
    location: "South Tukoganj",
    distance: "6.8",
    offers: 55,
    alcohol: false,
    restaurant_open_time: 9,
    restaurant_close_time: 21,
  },
  {
    image: "fourth",
    name: "Chutney & Co.",
    rating: "1.8",
    food_type: "Turkish",
    price_for_food: 358,
    location: "South Tukoganj",
    distance: "3.4",
    offers: 25,
    alcohol: false,
    restaurant_open_time: 19,
    restaurant_close_time: 7,
  },
  {
    image: "nine",
    name: "Chai & Chapati",
    rating: "3.1",
    food_type: "Japanese",
    price_for_food: 240,
    location: "New Palasia",
    distance: "8.4",
    offers: 21,
    alcohol: false,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "tenth",
    name: "Ganges Grill",
    rating: "1.3",
    food_type: "South Indian",
    price_for_food: 2367,
    location: "Rau",
    distance: "9.4",
    offers: 53,
    alcohol: false,
    restaurant_open_time: 18,
    restaurant_close_time: 6,
  },
  {
    image: "Eigth",
    name: "Chai & Chapati",
    rating: "1.2",
    food_type: "French",
    price_for_food: 511,
    location: "Vijay Nagar",
    distance: "3.5",
    offers: 32,
    alcohol: false,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "tenth",
    name: "Royal Darbar",
    rating: "4.0",
    food_type: "Thai",
    price_for_food: 1824,
    location: "Scheme 54",
    distance: "7.5",
    offers: 30,
    alcohol: false,
    restaurant_open_time: 10,
    restaurant_close_time: 22,
  },
  {
    image: "fourth",
    name: "Biryani House",
    rating: "1.6",
    food_type: "American",
    price_for_food: 616,
    location: "Sapna Sangeeta",
    distance: "8.5",
    offers: 44,
    alcohol: true,
    restaurant_open_time: 24,
    restaurant_close_time: 12,
  },
  {
    image: "third",
    name: "Royal Darbar",
    rating: "1.7",
    food_type: "Indian",
    price_for_food: 311,
    location: "South Tukoganj",
    distance: "10.2",
    offers: 33,
    alcohol: false,
    restaurant_open_time: 14,
    restaurant_close_time: 2,
  },
  {
    image: "fifth",
    name: "Punjabi Rasoi",
    rating: "2.4",
    food_type: "Fusion",
    price_for_food: 1826,
    location: "Geeta Bhawan",
    distance: "5.3",
    offers: 31,
    alcohol: false,
    restaurant_open_time: 7,
    restaurant_close_time: 19,
  },
  {
    image: "Eigth",
    name: "Chutney & Co.",
    rating: "3.7",
    food_type: "Japanese",
    price_for_food: 2206,
    location: "MG Road",
    distance: "2.3",
    offers: 51,
    alcohol: false,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "nine",
    name: "Punjabi Rasoi",
    rating: "3.0",
    food_type: "French",
    price_for_food: 2035,
    location: "Treasure Island Mall",
    distance: "2.8",
    offers: 14,
    alcohol: true,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "seventh",
    name: "Biryani House",
    rating: "3.3",
    food_type: "Mediterranean",
    price_for_food: 531,
    location: "Treasure Island Mall",
    distance: "8.5",
    offers: 9,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "fourth",
    name: "Chai & Chapati",
    rating: "3.0",
    food_type: "Vietnamese",
    price_for_food: 1735,
    location: "Bhawarkua",
    distance: "8.6",
    offers: 32,
    alcohol: false,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "nine",
    name: "Himalayan Hut",
    rating: "2.3",
    food_type: "Thai",
    price_for_food: 792,
    location: "MG Road",
    distance: "1.6",
    offers: 10,
    alcohol: false,
    restaurant_open_time: 7,
    restaurant_close_time: 19,
  },
  {
    image: "fourth",
    name: "Curry Leaf",
    rating: "4.2",
    food_type: "Mediterranean",
    price_for_food: 864,
    location: "Geeta Bhawan",
    distance: "3.3",
    offers: 20,
    alcohol: false,
    restaurant_open_time: 17,
    restaurant_close_time: 5,
  },
  {
    image: "First",
    name: "Punjabi Rasoi",
    rating: "4.8",
    food_type: "Mexican",
    price_for_food: 270,
    location: "Bhawarkua",
    distance: "6.9",
    offers: 34,
    alcohol: false,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "second",
    name: "Royal Darbar",
    rating: "4.6",
    food_type: "Greek",
    price_for_food: 1165,
    location: "Vijay Nagar",
    distance: "9.9",
    offers: 45,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "Eigth",
    name: "Thali Tales",
    rating: "2.1",
    food_type: "Korean",
    price_for_food: 2093,
    location: "South Tukoganj",
    distance: "4.7",
    offers: 17,
    alcohol: true,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "nine",
    name: "Spice Junction",
    rating: "1.8",
    food_type: "Vietnamese",
    price_for_food: 1244,
    location: "MG Road",
    distance: "3.5",
    offers: 27,
    alcohol: true,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "fifth",
    name: "Spice Junction",
    rating: "1.1",
    food_type: "Korean",
    price_for_food: 629,
    location: "New Palasia",
    distance: "7.6",
    offers: 46,
    alcohol: false,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "fifth",
    name: "Golden Temple Kitchen",
    rating: "2.6",
    food_type: "Continental",
    price_for_food: 774,
    location: "Treasure Island Mall",
    distance: "3.5",
    offers: 36,
    alcohol: true,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "Eigth",
    name: "Tandoori Nights",
    rating: "4.2",
    food_type: "Chinese",
    price_for_food: 259,
    location: "New Palasia",
    distance: "4.4",
    offers: 12,
    alcohol: true,
    restaurant_open_time: 9,
    restaurant_close_time: 21,
  },
  {
    image: "Eigth",
    name: "Thali Tales",
    rating: "3.9",
    food_type: "Fusion",
    price_for_food: 1002,
    location: "Bhawarkua",
    distance: "8.8",
    offers: 50,
    alcohol: true,
    restaurant_open_time: 10,
    restaurant_close_time: 22,
  },
  {
    image: "fourth",
    name: "Golden Temple Kitchen",
    rating: "2.4",
    food_type: "Thai",
    price_for_food: 2418,
    location: "South Tukoganj",
    distance: "3.5",
    offers: 23,
    alcohol: true,
    restaurant_open_time: 24,
    restaurant_close_time: 12,
  },
  {
    image: "First",
    name: "Spice Junction",
    rating: "4.9",
    food_type: "Lebanese",
    price_for_food: 102,
    location: "Bhawarkua",
    distance: "6.8",
    offers: 46,
    alcohol: false,
    restaurant_open_time: 10,
    restaurant_close_time: 22,
  },
  {
    image: "fifth",
    name: "Mango Masala",
    rating: "3.0",
    food_type: "Greek",
    price_for_food: 1115,
    location: "South Tukoganj",
    distance: "9.7",
    offers: 49,
    alcohol: false,
    restaurant_open_time: 16,
    restaurant_close_time: 4,
  },
  {
    image: "fifth",
    name: "Saffron Soul",
    rating: "4.5",
    food_type: "Japanese",
    price_for_food: 261,
    location: "Treasure Island Mall",
    distance: "6.2",
    offers: 33,
    alcohol: false,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "Eigth",
    name: "Tandoori Nights",
    rating: "2.8",
    food_type: "Mexican",
    price_for_food: 416,
    location: "Vijay Nagar",
    distance: "2.1",
    offers: 42,
    alcohol: false,
    restaurant_open_time: 23,
    restaurant_close_time: 11,
  },
  {
    image: "Eigth",
    name: "Thali Tales",
    rating: "3.4",
    food_type: "French",
    price_for_food: 1077,
    location: "Geeta Bhawan",
    distance: "10.9",
    offers: 13,
    alcohol: true,
    restaurant_open_time: 24,
    restaurant_close_time: 12,
  },
  {
    image: "fourth",
    name: "Kebab Kingdom",
    rating: "1.9",
    food_type: "Fusion",
    price_for_food: 1092,
    location: "South Tukoganj",
    distance: "4.5",
    offers: 21,
    alcohol: false,
    restaurant_open_time: 9,
    restaurant_close_time: 21,
  },
  {
    image: "Eigth",
    name: "Curry Leaf",
    rating: "1.9",
    food_type: "Vietnamese",
    price_for_food: 2252,
    location: "Vijay Nagar",
    distance: "2.7",
    offers: 38,
    alcohol: false,
    restaurant_open_time: 10,
    restaurant_close_time: 22,
  },
  {
    image: "seventh",
    name: "Royal Darbar",
    rating: "2.2",
    food_type: "Korean",
    price_for_food: 1418,
    location: "Scheme 54",
    distance: "9.9",
    offers: 24,
    alcohol: false,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "third",
    name: "Biryani House",
    rating: "3.9",
    food_type: "Middle Eastern",
    price_for_food: 2463,
    location: "Geeta Bhawan",
    distance: "10.6",
    offers: 19,
    alcohol: false,
    restaurant_open_time: 21,
    restaurant_close_time: 9,
  },
  {
    image: "seventh",
    name: "Punjabi Rasoi",
    rating: "1.3",
    food_type: "Italian",
    price_for_food: 823,
    location: "MG Road",
    distance: "5.3",
    offers: 54,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "sixth",
    name: "Saffron Soul",
    rating: "4.5",
    food_type: "Japanese",
    price_for_food: 230,
    location: "Sapna Sangeeta",
    distance: "3.1",
    offers: 49,
    alcohol: false,
    restaurant_open_time: 8,
    restaurant_close_time: 20,
  },
  {
    image: "First",
    name: "Royal Darbar",
    rating: "2.2",
    food_type: "Vietnamese",
    price_for_food: 1417,
    location: "Scheme 54",
    distance: "8.1",
    offers: 39,
    alcohol: true,
    restaurant_open_time: 13,
    restaurant_close_time: 1,
  },
  {
    image: "nine",
    name: "Thali Tales",
    rating: "4.5",
    food_type: "Lebanese",
    price_for_food: 2330,
    location: "Scheme 54",
    distance: "4.0",
    offers: 6,
    alcohol: false,
    restaurant_open_time: 22,
    restaurant_close_time: 10,
  },
  {
    image: "fifth",
    name: "Spice Junction",
    rating: "3.1",
    food_type: "North Indian",
    price_for_food: 820,
    location: "Treasure Island Mall",
    distance: "6.8",
    offers: 47,
    alcohol: false,
    restaurant_open_time: 9,
    restaurant_close_time: 21,
  },
  {
    image: "tenth",
    name: "Paneer Palace",
    rating: "1.2",
    food_type: "Turkish",
    price_for_food: 588,
    location: "Bhawarkua",
    distance: "9.4",
    offers: 49,
    alcohol: false,
    restaurant_open_time: 14,
    restaurant_close_time: 2,
  },
  {
    image: "third",
    name: "Thali Tales",
    rating: "3.2",
    food_type: "Mediterranean",
    price_for_food: 1795,
    location: "New Palasia",
    distance: "6.3",
    offers: 7,
    alcohol: false,
    restaurant_open_time: 12,
    restaurant_close_time: 0,
  },
  {
    image: "nine",
    name: "Chai & Chapati",
    rating: "2.1",
    food_type: "Korean",
    price_for_food: 951,
    location: "Geeta Bhawan",
    distance: "7.7",
    offers: 12,
    alcohol: false,
    restaurant_open_time: 16,
    restaurant_close_time: 4,
  },
  {
    image: "tenth",
    name: "Punjabi Rasoi",
    rating: "4.0",
    food_type: "Italian",
    price_for_food: 1265,
    location: "Treasure Island Mall",
    distance: "3.4",
    offers: 7,
    alcohol: true,
    restaurant_open_time: 14,
    restaurant_close_time: 2,
  },
  {
    image: "nine",
    name: "Tandoori Nights",
    rating: "1.3",
    food_type: "Japanese",
    price_for_food: 425,
    location: "Bhawarkua",
    distance: "7.5",
    offers: 51,
    alcohol: false,
    restaurant_open_time: 17,
    restaurant_close_time: 5,
  },
  {
    image: "tenth",
    name: "Saffron Soul",
    rating: "1.8",
    food_type: "North Indian",
    price_for_food: 676,
    location: "South Tukoganj",
    distance: "8.8",
    offers: 46,
    alcohol: false,
    restaurant_open_time: 10,
    restaurant_close_time: 22,
  },
  {
    image: "nine",
    name: "Biryani House",
    rating: "1.1",
    food_type: "Mediterranean",
    price_for_food: 934,
    location: "Rau",
    distance: "9.6",
    offers: 48,
    alcohol: false,
    restaurant_open_time: 15,
    restaurant_close_time: 3,
  },
  {
    image: "second",
    name: "Thali Tales",
    rating: "1.1",
    food_type: "Italian",
    price_for_food: 780,
    location: "Geeta Bhawan",
    distance: "6.7",
    offers: 29,
    alcohol: false,
    restaurant_open_time: 20,
    restaurant_close_time: 8,
  },
  {
    image: "third",
    name: "Spice Junction",
    rating: "1.6",
    food_type: "Indian",
    price_for_food: 678,
    location: "Treasure Island Mall",
    distance: "6.5",
    offers: 29,
    alcohol: false,
    restaurant_open_time: 23,
    restaurant_close_time: 11,
  },
];

function getRestaurants(restaurants) {
  const root = document.getElementById("root");

  restaurants.forEach((restaurant) => {
    //* Create a card.
    const card = document.createElement("div");
    card.classList.add("card");

    //* 1: Image.
    const image = document.createElement("img");
    image.src = `./Images/${restaurant.image}.jpeg`;

    //* 2: Card Content.
    const cardContent = document.createElement("div");
    cardContent.classList.add("card-content");

    //* 2.1. Card Header.
    const cardHeader = document.createElement("div");
    cardHeader.classList.add("card-header");

    //* 2.1.1: Name.
    const h3 = document.createElement("h3");
    h3.textContent = restaurant.name;

    //* 2.1.2: Rating.
    const rate = document.createElement("span");
    rate.classList.add("rating");
    rate.textContent = `${restaurant.rating}*`;

    //* 2.2: Card Footer.
    const cardFooter = document.createElement("div");
    cardFooter.classList.add("card-footer");

    cardHeader.appendChild(h3);
    cardHeader.appendChild(rate);

    //* 2.2.1: Food Type.
    const food = document.createElement("span");
    food.textContent = restaurant.food_type;

    //* 2.2.2: Price.
    const price = document.createElement("span");
    price.textContent = `₹${restaurant.price_for_food}`;

    cardFooter.appendChild(food);
    cardFooter.appendChild(price);

    //* 2.3: Card Location.
    const cardLocation = document.createElement("div");
    cardLocation.classList.add("card-location");

    //* 2.3.1: Restaurant Location.
    const location = document.createElement("span");
    location.textContent = restaurant.location;

    //* 2.3.2: Distance.
    const distance = document.createElement("span");
    distance.textContent = `${restaurant.distance}km`;

    cardLocation.appendChild(location);
    cardLocation.appendChild(distance);

    // Add to card content.
    cardContent.appendChild(cardHeader);
    cardContent.appendChild(cardFooter);
    cardContent.appendChild(cardLocation);

    // Add to card.
    card.appendChild(image);
    card.appendChild(cardContent);

    // Add card to HTML id="root"
    root.appendChild(card);
  });
}

getRestaurants(restaurants);

document.getElementById("Alcohol").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.alcohol);

  //   document.getElementById("root").innerHTML = "";
  document.getElementById("root").replaceChildren(); // This will replace all the children & make it empty.

  getRestaurants(result);
});

document.getElementById("Rating").addEventListener("click", () => {
  const result = restaurants.filter((obj) => obj.rating >= 4.5);

  document.getElementById("root").replaceChildren();

  getRestaurants(result);
});

document.getElementById("Filters").addEventListener("click", () => {
  //* Remove the class or display="block".
  //   document.getElementById("filterPopup").classList.remove("hidden");

  document.getElementById("filterPopup").style.display = "block";
});

document.getElementById("closeFilter").addEventListener("click", () => {
  document.getElementById("filterPopup").style.display = "none";
});

document.getElementById("applyFilter").addEventListener("click", () => {
  const element = document.querySelector("input[name='filterOption']:checked");
  const answer = element.value;

  if (answer == "rating") {
    restaurants.sort((a, b) => b.rating - a.rating);
  } else if (answer == "highLow") {
    restaurants.sort((a, b) => b.price_for_food - a.price_for_food);
  } else if (answer == "costLowHigh") {
    restaurants.sort((a, b) => a.price_for_food - b.price_for_food);
  } else if (answer == "distance") {
    restaurants.sort((a, b) => a.distance - b.distance);
  }

  document.getElementById("root").replaceChildren();

  document.getElementById("filterPopup").style.display = "none";

  getRestaurants(restaurants);
});
